version: '3'

volumes:
  output-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /REPLACE_ME/PATH/TO/output_descriptions #TODO

services:
  cookie-thing:
    build:
      context: .
    restart: always
    volumes:
      - output-data:/app/output_descriptions
    environment:
      - FLASK_ENV=production
    ports:
      - 5000:5000

